### ISSUE TITLE
Getting the code tour generator working again

### ISSUE THREAD

**Issue by Sophira** [dreamwidth/dreamhack#23]
I'm working on fixing up the code tour generator for GitHub.

I'm going to build out a spec for precisely how the generator will work before doing work on it. This is something I should have done a long time ago, but the only things I did were talking about its implementation on IRC, where it's not easy to refer to it. So I'll try to consolidate all of that and present it here for everybody's reference.

I also recently had an idea on how to improve the process - we should have a branch that's updated every time a code tour is posted in dw_dev, signifying the latest commit included in that code tour. The code tour generator would then be able to use that next time round to easily (and exactly) work out where the next code tour needs to begin. To me, this seems to make sense.

What do people think?

**Comment by kareila** [comment]
I believe this can be closed? It's been working for some time now.

**Comment by Sophira** [comment]
You're right, oops. For some reason I missed this!
